server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route for testing api-gateway
            - id: test-route
              uri: https://httpbin.org
              predicates:
                - Path=/test

            # Route for /auth/** to auth-service
            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            # Route for api-docs to auth-service
            - id: api-docs-auth-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs

            # Route for /api/patients/** to patient-service
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE